[package]
name = "minimint-bridge"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
anyhow = "1"
mint-client = { path = "../../minimint/client/client-lib/"}
minimint-api = { path = "../../minimint/minimint-api/" }
minimint-core = { path = "../../minimint/minimint-core/" }
futures = "0.3"

serde_json = "1.0.61"
# secp256k1-zkp = { git = "https://github.com/elsirion/rust-secp256k1-zkp", branch = "minimint", features = [ "serde", "bitcoin_hashes" ] }
rand = { version = "0.6.5", features = ["wasm-bindgen"] }
# bitcoincore-rpc = "0.15.0"
bitcoin = "0.28.1"
# hex = "0.4.3"
# log = "0.4.16"
lazy_static = "1.4.0"
reqwest = { version = "0.11.0", features = [ "json" ], default-features = false }
lightning-invoice = "0.17.0"
# lightning = "0.0.106"

tracing = "0.1.26"
js-sys = "0.3.59"
getrandom = { version = "0.1.16", features = ["wasm-bindgen"] }
serde = { version = "1.0.143", features = ["derive"] }
# tracing-subscriber = { version = "0.3.1", features = [ "env-filter" ] }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
tracing-subscriber = { version = "0.3.1", features = [ "env-filter" ] }
flutter_rust_bridge = "1"
sled = "0.34.6"
tokio = {version = "1.0", features = ["full"]}

[target.'cfg(target_family = "wasm")'.dependencies]
js-sys = "0.3.59"
rexie = "0.4.2"
tracing-wasm = "0.2.1"
wasm-bindgen = "0.2.82"
wasm-bindgen-futures = "0.4.32"

[target.'cfg(target_os = "ios")'.dependencies]
tracing-oslog = "0.1.2"

[target.'cfg(target_os = "android")'.dependencies]
paranoid-android = { git = "https://github.com/justinmoon/paranoid-android", branch="c_char" }

[patch.crates-io]
bitcoin_hashes = { version = "0.10.0", git = 'https://github.com/fedimint/bitcoin_hashes', branch = 'minimint' }
secp256k1-zkp = { git = "https://github.com/fedimint/rust-secp256k1-zkp/", branch = "sanket-pr" }
